// DEVICE INTERFACE

struct ButtonStruct {
    Yes:                bool,       // True if button is pressed
    No:                 bool,       // True if button is pressed
}

// EXPORT
export global Device {
    in-out property <ButtonStruct> Button: {    
        Yes: false, 
        No: false
    };

    callback handlerButtonReleased(string);         // Implemented in UI
    
    // Action handler for button released
    handlerButtonReleased(ButtonID) => {  
        debug("UI impl - Device.handlerButtonReleased ButtonID:", ButtonID);  
    }
}