import { Button, VerticalBox, HorizontalBox, GroupBox } from "std-widgets.slint";

// INTERFACE IMPORT
import { CallInterface, DeviceInterface } from "./Interfaces.slint"; 
export { CallInterface, DeviceInterface }  

export component MainWindow inherits Window {
    title: "invoke_from_event_loop nested test";
    preferred-width: 520px;
    preferred-height: 280px;

    in-out property <string> status_text: "Idle. Press a button to start a thread.";

    property <bool> yesButtonPressed : DeviceInterface.Button.Yes;
    property <bool> noButtonPressed : DeviceInterface.Button.No;

    callback simulate_press(string);    // Simulate Press       // string->ButtonID
    callback simulate_release(string);  // Simulate Release     // string->ButtonID


    changed yesButtonPressed => {   
        debug("UI - yesButtonPressed value : ", yesButtonPressed);
        if(!yesButtonPressed) { // If the button is released
            CallInterface.signalSendMessage("1", "Yes Button clicked"); // (Changed value ensures false clicks donot happen)
        }
    }

    changed noButtonPressed => {
        debug("UI - noButtonPressed value : ", noButtonPressed);
        if(!noButtonPressed) { // If the button is released
            CallInterface.signalSendMessage("1", "No Button clicked");  // (Changed value ensures false clicks donot happen)
        }
    }

    VerticalBox {
        spacing: 12px;
        padding: 16px;

        HorizontalBox {
            spacing: 8px;

            yesButton := Rectangle {
                property <string> buttonID : "yes";
                background: (yesButtonPressed || taYes.pressed) ? #228029 : #00ff00;
                width: 100px;
                height: 50px;
                
                Text {
                    text: "Yes";
                }
    
                taYes := TouchArea {
                    clicked => {
                        CallInterface.signalSendMessage("1", "Yes Button clicked");
                    }
                }
            }

            HorizontalBox {
            
                spacing: 8px;
                Button {
                    // height: 50px;
                    text: "Simulate Press";
                    clicked => { 
                        debug("UI - Simulating Press - Yes");
                        root.simulate_press(yesButton.buttonID);
                     }
                }
                Button {
                    // height: 50px;
                    text: "Simulate Release";
                    clicked => { 
                        debug("UI - Simulating Release - Yes");
                        root.simulate_release(yesButton.buttonID); 
                    }
                }
    
            }
        }


        HorizontalBox {
            spacing: 8px;

            noButton := Rectangle {
                property <string> buttonID : "no";
                background: (noButtonPressed || taNo.pressed) ? #802222 : #da4a4a;
                width: 100px;
                height: 50px;
                
                Text {
                    text: "No";
                }
    
                taNo := TouchArea {
                    clicked => {
                        CallInterface.signalSendMessage("1", "No Button clicked");
                    }
                }
            }

            HorizontalBox {
            
                spacing: 8px;
                Button {
                    // height: 50px;
                    text: "Simulate Press";
                    clicked => { 
                        debug("UI - Simulating Press - No");
                        root.simulate_press(noButton.buttonID);
                     }
                }
                Button {
                    // height: 50px;
                    text: "Simulate Release";
                    clicked => { 
                        debug("UI - Simulating Release - No");
                        root.simulate_release(noButton.buttonID); 
                    }
                }
    
            }
        }





    }
}
